apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: px-hdd-ha1-rwx
parameters:
  force_unsupported_fs_type: "true"
  fs: "xfs"
  priority_io: "low"
  repl: "1"
  shared: "true"
provisioner: kubernetes.io/portworx-volume
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: px-hdd-ha2-rwx
parameters:
  force_unsupported_fs_type: "true"
  fs: "xfs"
  priority_io: "low"
  repl: "2"
  shared: "true"
provisioner: kubernetes.io/portworx-volume
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: px-hdd-ha3-rwx
parameters:
  force_unsupported_fs_type: "true"
  fs: "xfs"
  priority_io: "low"
  repl: "3"
  shared: "true"
provisioner: kubernetes.io/portworx-volume
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: px-ssd-ha1-rwx
parameters:
  force_unsupported_fs_type: "true"
  fs: "xfs"
  priority_io: "high"
  repl: "1"
  shared: "true"
provisioner: kubernetes.io/portworx-volume
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: px-ssd-ha2-rwx
parameters:
  force_unsupported_fs_type: "true"
  fs: "xfs"
  priority_io: "high"
  repl: "2"
  shared: "true"
provisioner: kubernetes.io/portworx-volume
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: px-ssd-ha3-rwx
parameters:
  force_unsupported_fs_type: "true"
  fs: "xfs"
  priority_io: "high"
  repl: "3"
  shared: "true"
provisioner: kubernetes.io/portworx-volume

