apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: px-hdd-ha1-rwo
parameters:
  force_unsupported_fs_type: "true"
  fs: "xfs"
  priority_io: "low"
  repl: "1"
provisioner: kubernetes.io/portworx-volume
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: px-hdd-ha2-rwo
parameters:
  force_unsupported_fs_type: "true"
  fs: "xfs"
  priority_io: "low"
  repl: "2"
provisioner: kubernetes.io/portworx-volume
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: px-hdd-ha3-rwo
parameters:
  force_unsupported_fs_type: "true"
  fs: "xfs"
  priority_io: "low"
  repl: "3"
provisioner: kubernetes.io/portworx-volume
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: px-ssd-ha1-rwo
parameters:
  force_unsupported_fs_type: "true"
  fs: "xfs"
  priority_io: "high"
  repl: "1"
provisioner: kubernetes.io/portworx-volume
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: px-ssd-ha2-rwo
parameters:
  force_unsupported_fs_type: "true"
  fs: "xfs"
  priority_io: "high"
  repl: "2"
provisioner: kubernetes.io/portworx-volume
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: px-ssd-ha3-rwo
parameters:
  force_unsupported_fs_type: "true"
  fs: "xfs"
  priority_io: "high"
  repl: "3"
provisioner: kubernetes.io/portworx-volume

