apiVersion: v1
kind: ServiceAccount
metadata:
  name: px-csi-account
  namespace: kube-system

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
   name: px-csi-role
rules:
- apiGroups: ["extensions"]
  resources: ["podsecuritypolicies"]
  resourceNames: ["privileged"]
  verbs: ["use"]
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["persistentvolumes"]
  verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "list", "watch", "update"]
- apiGroups: [""]
  resources: ["persistentvolumeclaims/status"]
  verbs: ["update", "patch"]
- apiGroups: ["storage.k8s.io"]
  resources: ["storageclasses"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["storage.k8s.io"]
  resources: ["volumeattachments"]
  verbs: ["get", "list", "watch", "update", "patch"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["list", "watch", "create", "update", "patch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
- apiGroups: ["snapshot.storage.k8s.io"]
  resources: ["volumesnapshots", "volumesnapshotcontents", "volumesnapshotclasses", "volumesnapshots/status"]
  verbs: ["create", "get", "list", "watch", "update", "delete"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["storage.k8s.io"]
  resources: ["csinodes"]
  verbs: ["get", "list", "watch", "update"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["csi.storage.k8s.io"]
  resources: ["csidrivers"]
  verbs: ["create", "delete"]
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get", "watch", "list", "delete", "update", "create"]
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["*"]

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: px-csi-role-binding
subjects:
- kind: ServiceAccount
  name: px-csi-account
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: px-csi-role
  apiGroup: rbac.authorization.k8s.io

---

kind: Service
apiVersion: v1
metadata:
  name: px-csi-service
  namespace: kube-system
spec:
  clusterIP: None

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: px-csi-ext
  namespace: kube-system
spec:
  replicas: 3
  selector:
    matchLabels:
      app: px-csi-driver
  template:
    metadata:
      labels:
        app: px-csi-driver
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: px/enabled
                operator: In
                values:
                - "true"
              - key: node-role.kubernetes.io/master
                operator: DoesNotExist
      serviceAccount: px-csi-account
      containers:
        - name: csi-external-provisioner
          imagePullPolicy: IfNotPresent
          image: daocloud.io/portworx/csi-provisioner:v1.3.0-1
          args:
            - "--v=3"
            - "--provisioner=com.openstorage.pxd"
            - "--csi-address=$(ADDRESS)"
            - "--enable-leader-election"
            - "--leader-election-type=leases"
          env:
            - name: ADDRESS
              value: /csi/csi.sock
          securityContext:
            privileged: true
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
###################################
######## Added by DaoCloud ########
            - name: localtime
              mountPath: /etc/localtime
###################################
###################################
######## Added by DaoCloud ########
          resources:
            # requests:
            #   cpu: '500m'
            #   memory: '500Mi'
            limits:
              cpu: '1'
              memory: '1Gi'
###################################
        - name: csi-snapshotter
          imagePullPolicy: IfNotPresent
          image: daocloud.io/portworx/csi-snapshotter:v1.2.0-1
          args:
            - "--v=3"
            - "--csi-address=$(ADDRESS)"
            - "--snapshotter=com.openstorage.pxd"
            - "--leader-election=true"
            - "--leader-election-type=leases"
          env:
            - name: ADDRESS
              value: /csi/csi.sock
          securityContext:
            privileged: true
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
###################################
######## Added by DaoCloud ########
            - name: localtime
              mountPath: /etc/localtime
###################################
###################################
######## Added by DaoCloud ########
          resources:
            # requests:
            #   cpu: '500m'
            #   memory: '500Mi'
            limits:
              cpu: '1'
              memory: '1Gi'
###################################
        - name: csi-resizer
          imagePullPolicy: IfNotPresent
          image: daocloud.io/portworx/csi-resizer:v0.2.0-1
          args:
            - "--v=3"
            - "--csi-address=$(ADDRESS)"
            - "--leader-election=true"
          env:
            - name: ADDRESS
              value: /csi/csi.sock
          securityContext:
            privileged: true
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
###################################
######## Added by DaoCloud ########
            - name: localtime
              mountPath: /etc/localtime
###################################
###################################
######## Added by DaoCloud ########
          resources:
            # requests:
            #   cpu: '500m'
            #   memory: '500Mi'
            limits:
              cpu: '1'
              memory: '1Gi'
###################################
      volumes:
        - name: socket-dir
          hostPath:
            path: /var/lib/kubelet/plugins/com.openstorage.pxd
            type: DirectoryOrCreate
###################################
######## Added by DaoCloud ########
        - name: localtime
          hostPath:
            path: /etc/localtime
###################################
######## Added by DaoCloud ########
#      imagePullSecrets:
#        - name: "portworx-regcred"
###################################

---

kind: Service
apiVersion: v1
metadata:
  name: portworx-api
  namespace: kube-system
  labels:
    name: portworx-api
spec:
  selector:
    name: portworx-api
  type: NodePort
  ports:
    - name: px-api
      protocol: TCP
      port: 9001
      targetPort: 9001
    - name: px-sdk
      protocol: TCP
      port: 9020
      targetPort: 9020
    - name: px-rest-gateway
      protocol: TCP
      port: 9021
      targetPort: 9021

---

apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: portworx-api
  namespace: kube-system
spec:
  minReadySeconds: 0
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 100%
  template:
    metadata:
      labels:
        name: portworx-api
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: px/enabled
                operator: In
                values:
                - "true"
              - key: node-role.kubernetes.io/master
                operator: DoesNotExist
      hostNetwork: true
      hostPID: false
      containers:
        - name: portworx-api
          image: daocloud.io/portworx/pause:3.1
          imagePullPolicy: IfNotPresent
          readinessProbe:
            periodSeconds: 10
            httpGet:
              host: 127.0.0.1
              path: /status
              port: 9001
###################################
######## Added by DaoCloud ########
          resources:
            # requests:
            #   cpu: '50m'
            #   memory: '50Mi'
            limits:
              cpu: '100m'
              memory: '100Mi'
###################################
      restartPolicy: Always
      serviceAccountName: px-account

---

apiVersion: storage.k8s.io/v1beta1
kind: CSIDriver
metadata:
  name: com.openstorage.pxd
spec:
  attachRequired: false
  podInfoOnMount: false
